### PR TITLE
use decimals in account balance

### LINKED ISSUE #920: Use token decimals when getting the balance
**Describe the bug**

When getting a token balance, make sure that we read the number of decimals and use it 

**To Reproduce**
https://github.com/oceanprotocol/ocean.js/blob/bfbd11a83ba4d0de58204390d43201b444a57b2d/src/ocean/Account.ts#L82-L117
This implies that all tokens have 18 decimals

### PR DESCRIPTION
**Pull request by alexcos20**
Closes #920 
When getting a token balance, make sure that we read the number of decimals and use it

### CODE REVIEW

File: src/ocean/Account.ts [hunk 1]
```diff
@@ -104,18 +104,47 @@ export default class Account extends Instantiable {
...
     let result = null
-
+    const decimals = await this.getTokenDecimals(TokenAdress)
     try {
       const token = new this.web3.eth.Contract(minABI, TokenAdress, {
         from: this.id
       })
-      result = this.web3.utils.fromWei(await token.methods.balanceOf(this.id).call())
+      const balance = await token.methods.balanceOf(this.id).call()
+      result = balance.div(10 ** decimals).toString()
```
Comment (krisliew) [inline src/ocean/Account.ts:113]: `balance.div(` is not working here.
I tried replacing with `result = balance / 10 ** decimals` and it worked perfectly.

**Review by krisliew — APPROVED** [review]
Tested working perfectly! 👍
